# Builder stage
FROM maven:3.8.2-openjdk-17-slim AS builder
WORKDIR /app
COPY . .
RUN mvn clean package

# Production stage
FROM openjdk:17-slim
COPY --from=builder /app/target/*.jar /app.jar
EXPOSE 8072
ENTRYPOINT ["java","-jar","/app.jar"]
